### ISSUE TITLE
Estilos CSS en hoja central 

### ISSUE THREAD

**Issue by davidcr01** [davidcr01/Class4All#15]
Al principio en los primeros ficheros, al no saber mucho del tema poníamos los estilos de los componentes directamente en vez de en la hoja de estilos central. Esto puede estar bien pero si es un patrón que se repite habría que cambiarlo. Hay bastantes complementos con los estilos inline por el copia y pega.

### A realizar. EDITADO por Javier Serrano

**Propongo que, ya que tenemos que estructurar en vistas y tal los componentes, crear una hoja de estilo por página (o similar).
Si no la hoja de estilos centralizada va a crecer mucho y además los nombres de las clases van a acabar por tener que ser muy específicos y va a ser difícil encontrarnos**

**Comment by javierSerLuc** [comment]
Propongo además, ya que tenemos que estructurar en vistas y tal los componentes, crear una hoja de estilo por página (o similar).
Si no la hoja de estilos centralizada va a crecer mucho y además los nombres de las clases van a acabar por tener que ser muy específicos y va a ser difícil encontrarnos

**Comment by davidcr01** [comment]
Cerrado en https://github.com/davidcr01/Class4All/pull/47
