### ISSUE TITLE
Eliminar flechas cuando una clase esté vacía

### ISSUE THREAD

**Issue by davidcr01** [davidcr01/Class4All#48]
## Descripción

Cuando en una clase no existen alumnos, las flechas de paginación siguen apareciendo en la app. 
Lo ideal sería que las flechas aparecieran siempre que:
- haya más de un elemento 
- o bien siempre que haya más de N elementos, donde N es el número máximo de elementos que se pueden mostrar en pantalla. En nuestro caso son 4.

**Comment by amt911** [comment]
Arreglado, hace exactamente lo que dices y además funciona para las dos pantallas (clases y alumnos).
