### ISSUE TITLE
Agrupar componentes y páginas

### ISSUE THREAD

**Issue by javierSerLuc** [davidcr01/Class4All#5]
# Issue Agrupar componentes
Me he dado cuenta de que la separación de componentes en plantillas y páginas no va a ser suficiente. Si nos fijamos las carpetas tanto de páginas como de layout van a crecer mucho y buscar algún fichero en concreto va a ser difícil. Por eso propongo agruparlos más

### Paginas
En principio las páginas vamos a agruparlas en vistas de alumno/profesor/administradores. Si no fuera suficiente eso también podemos agruparlas dentro dependiendo de a funcionalidad, se aceptan sugerencias.

### Layout
Aquí sugiero lo mismo. En principio la mayoría de componentes van a ser únicos dependiendo de la vista. De la misma manera deberíamos pensar en agrupar por funcionalidades, pensad en una solución de agrupación bien definida y estructurada

**Comment by davidcr01** [comment]
https://github.com/davidcr01/Class4All/pull/45
