### ISSUE TITLE
Refactorizar componentes con JSX

### ISSUE THREAD

**Issue by javierSerLuc** [davidcr01/Class4All#6]
# ISSUE JSX vs JS

Revisando el código de los componentes he visto que no he tomado la mejor decisión de diseño respecto a la programación de componentes. Intercambié los conceptos de JSX y JS a pelo. Es mejor JSX sin el createElement, ya que nos permite tener un código más limpio e intuitivo. Por suerte he caído en esta decisión relativamente pronto. Propongo usar JSX a partir de ahora y cambiar los componentes que no lo o usan. No es una tarea complicada, ni hay que instalar nada.

### Ejemplo de código que usa JSX
Aquí se usan 2 return para mostrar un mensaje de inexistencia de objetos en un array pero en esencia es lo mismo
#### https://github.com/javierSerLuc/React-learning/blob/master/proyecto_pelis_01/src/components/Listado.js
![ejempllo](https://user-images.githubusercontent.com/100939287/199458045-5fcedd96-b7b3-4fa4-961b-112b7ea955b7.JPG)

**Comment by davidcr01** [comment]
Realizado por Sergio y por mi
